---
title: "565_Final_Feature"
author: "KyungjinSohn"
date: '2022 4 9 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
```

## Combine feature extraction results

```{r}
ngram.title <- read.csv("../data/Feature_extraction/ngram_title.csv", header = TRUE)
colnames(ngram.title)[1:2] <- c("title", "id")
colnames(ngram.title)[3:ncol(ngram.title)] <- paste0(colnames(ngram.title)[3:ncol(ngram.title)], "_title")
ngram.text <- read.csv("../data/Feature_extraction/ngram_text.csv", header = TRUE)
colnames(ngram.text)[1:2] <- c("text", "id")
colnames(ngram.text)[3:ncol(ngram.text)] <- paste0(colnames(ngram.text)[3:ncol(ngram.text)], "_text")
sentiment.fake <- read.csv("../data/Feature_extraction/Fake_sentiment.csv", header = TRUE)
sentiment.true <- read.csv("../data/Feature_extraction/True_sentiment.csv", header = TRUE)
sentiment.full <- rbind(sentiment.fake, sentiment.true)
          
feature.full <- full_join(ngram.title, ngram.text)
feature.full <- full_join(feature.full, sentiment.full)

feature.full <- feature.full %>%
          select(id, title, text, everything())

write.csv(feature.full, file ="../data/Feature_extraction/Full_Feature_extraction.csv", row.names = FALSE)
```
